version: "{branch}-ci-{build}"
os: Visual Studio 2015

branches:
  only:
    - master
    - master1.1
    - test

environment:
  matrix:
    - CMAKE_GENERATOR: 'MinGW Makefiles'
      MINGW_ROOT: C:\Qt\Tools\mingw530_32
      QT_DIR: C:\Qt\5.9\mingw53_32
      BOOST_ROOT: C:\Libraries\boost_1_63_0

init:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

install:
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-i686-libxml2"

before_build:
  - set PATH=%MINGW_ROOT%\bin;%QT_DIR%\bin;%PATH%
  - set VLEDEPS_BASEPATH=C:\msys64\mingw32
  - set prefix=%APPVEYOR_BUILD_FOLDER%\release

build_script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -G "%CMAKE_GENERATOR%" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DWITH_MVLE=OFF -DWITH_CVLE=OFF -DWITH_DOXYGEN=OFF -DWITH_GVLE=ON -DWITH_WIN32_INSTALLER=OFF -DCMAKE_INSTALL_PREFIX="%prefix%" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QT_DIR%" ..
  - cmake --build build
  - cmake --build build --target install

after_build:
  - windeployqt --list mapping --compiler-runtime --dir %prefix% %prefix%\bin\gvle.exe
  - xcopy -s -i -y C:/msys64/mingw32/bin/libxml2-2.dll %prefix%\bin
  - xcopy -s -i -y C:/msys64/mingw32/bin/zlib1.dll %prefix%\bin
  - xcopy -s -i -y C:/msys64/mingw32/bin/libiconv-2.dll %prefix%\bin
  - xcopy -s -i -y C:/msys64/mingw32/bin/libintl-8.dll %prefix%\bin
  - xcopy -s -i -y C:/msys64/mingw32/lib/libxml2.dll.a %prefix%\lib
  - xcopy -s -i -y C:/msys64/mingw32/lib/libz.dll.a %prefix%\lib
  - xcopy -s -i -y C:/msys64/mingw32/lib/libiconv.dll.a %prefix%\lib
  - xcopy -s -i -y C:/msys64/mingw32/lib/libintl.dll.a %prefix%\lib
  - md %prefix%/mingw530_32
  - xcopy -s -i -y %MINGW_ROOT% %prefix%/mingw530_32
  - cmake --build build --target package
  - 7z a vle.zip %APPVEYOR_BUILD_FOLDER%\build\*.exe
  - xcopy -s -i -y c:\Program Files\CMake %prefix%\

test_script:
  - set PATH=%prefix%\bin;%PATH%
  - set CTEST_OUTPUT_ON_FAILURE=ON

artifacts:
  - path: vle.zip
    name: app
